# .github/workflows/update-formula.yml

name: Update Homebrew Formula

on:
  repository_dispatch:
    types: [update-formula]


permissions:
  contents: write

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update formula
        run: |
          python3 version_bump.py --version ${{ github.event.client_payload.version }} --hash-linux ${{ github.event.client_payload.hash_linux }} --hash-mac-intel  ${{ github.event.client_payload.hash_mac_intel }} --hash-mac-arm ${{ github.event.client_payload.hash_mac_arm }} --hash-windows ${{ github.event.client_payload.hash_windows }} ${{ github.event.client_payload.nightly && '--nightly' || '' }}

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions